### PR TITLE
Re-Add Firefox Warning, add link to chrome, and make text friendier in an attempt to get people to read welcome message

### PR DESCRIPTION
**Pull request by awdev1**
# Changelog
## 2024-08-18:
Added:
- Updated Firefox notification message to include a clickable link for chrome. Users/5yr olds should be taken to the Chrome download page.
- Added a please read me message.

Changes:
- Modified the content of notification message to be a little more friendly and as said before chrome link added
- Modified text for bolding and and friendliness

Tested and signed,
awdev1

### CODE REVIEW

**Comment by awdev1** [comment]
No conflicts and tested locally

**Comment by CrossTR15YT** [comment]
Grammar mistake. First point of the "Added" section has Chrome spelt as "chrome". It is missing a capital letter.

**Comment by awdev1** [comment]
Oh no my social credit

**Comment by Zedruc** [comment]
Appquested as Removed

**Pull request merged**
