### PR TITLE
Update Mellor airport data

### PR DESCRIPTION
**Pull request by CrossTR15YT**
- Removed CTR frequency from Mellor airport due to ATC24 rules
- Took me 15 minutes

### CODE REVIEW

**Comment by awdev1** [comment]
That appears to be good and ready to commit but who knows it might take down production.

**Comment by FormicAcidGD** [comment]
On my dev version of this PR the radar doesn’t work and it took down my entire network and injected faulty drivers into all my computers but it LGMT!

**Comment by Zedruc** [comment]
Finally someone removed this so atc24 users have to use one braincell less 💯

Approved as requested

**Comment by awdev1** [comment]
Awesome glad someone did something instead of complaining about it

**Comment by awdev1** [comment]
> On my dev version of this PR the radar doesn’t work and it took down my entire network and injected faulty drivers into all my computers but it LGTM!

My fritzbox new up too!

**Comment by Zedruc** [comment]
> > On my dev version of this PR the radar doesn’t work and it took down my entire network and injected faulty drivers into all my computers but it LGTM!
> 
> My fritzbox blew up too!

Microsoft just called me, the PR shut down Berlin airport agaib

**Comment by awdev1** [comment]
> > > On my dev version of this PR the radar doesn’t work and it took down my entire network and injected faulty drivers into all my computers but it LGTM!
> > 
> > My fritzbox blew up too!
> 
> Microsoft just called me, the PR shut down Berlin airport agaib

ICANN and Cloudflare just called me: we took down every domain in the world!?!??????!1!1!?

**Pull request merged**
